# Generated by Django 3.2.4 on 2021-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicval', '0002_diccionario_no_de_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diccionario',
            name='palabra',
            field=models.CharField(max_length=250),
        ),
    ]
